import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "black",
        alignItems: "center",
        top: 130,
      },
      loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "black",
      },
      loadingText: {
        marginTop: 10,
        fontSize: 16,
        color: "#333",
      },
      header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingVertical: 15,
        backgroundColor: "black",
        borderBottomWidth: 1,
        borderBottomColor: "#eee",
      },
      headerTitle: {
        fontSize: 22,
        fontWeight: "bold",
        color: "#333",
      },
      newChallengeButton: {
        backgroundColor: "#007AFF",
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
      },
      listContent: {
        paddingBottom: 500,
      },
      streakContainer: {
        flexDirection: "row",
        marginVertical: 10,
        padding: 15,
        borderRadius: 35,
        marginHorizontal: 10,
      },
      streakLeftBox: {
        width: "30%",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 10,
      },
      flameIconContainer: {
        marginBottom: 5,
      },
      streakDaysCount: {
        fontSize: 22,
        fontWeight: "bold",
        color: "white",
        textAlign: "center",
      },
      streakDaysLabel: {
        fontSize: 14,
        color: "#aaa",
        textAlign: "center",
      },
      streakRightContent: {
        width: "70%",
        paddingLeft: 10,
      },
      pointsContainer: {
        flexDirection: "row",
        alignItems: "baseline",
      },
      pointsText: {
        fontSize: 28,
        fontWeight: "bold",
        color: "white",
      },
      pointsLabel: {
        fontSize: 18,
        color: "#aaa",
        marginLeft: 5,
      },
      progressBarContainer: {
        height: 16,
        backgroundColor: "#333",
        borderRadius: 10,
        marginVertical: 15,
        overflow: "hidden",
      },
      progressBar: {
        height: "100%",
        backgroundColor: "white",
        borderRadius: 10,
      },
      weekdayContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 5,
      },
      dayCircle: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
      },
      dayLabelsContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
      },
      dayLabel: {
        fontSize: 12,
        color: "white",
        textAlign: "center",
        fontWeight: "bold",
      },
      todayChallengeCard: {
        padding: 15,
        marginHorizontal: 10,
        borderRadius: 30,
      },
      cardHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 10,
      },
      cardTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "white",
      },
      completedBadge: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#28a745",
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 12,
      },
      completedText: {
        color: "white",
        fontWeight: "bold",
        marginLeft: 4,
        fontSize: 12,
      },
      takeButton: {
        backgroundColor: "#007AFF",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
      },
      takeButtonText: {
        color: "white",
        fontWeight: "bold",
        fontSize: 12,
      },
      challengeDesc: {
        fontSize: 16,
        color: "white",
        marginBottom: 10,
      },
      challengeDetails: {
        flexDirection: "row",
        justifyContent: "space-between",
      },
      challengeClass: {
        fontSize: 14,
        color: "white",
      },
      challengeExpiry: {
        fontSize: 14,
        color: "#ff6b6b",
        fontWeight: "500",
      },
      historyHeader: {
        marginHorizontal: 15,
        marginTop: 25,
        marginBottom: 5,
      },
      historyHeaderText: {
        fontSize: 18,
        fontWeight: "bold",
        color: "white",
      },
      historyItem: {
        marginHorizontal: 15,
        marginTop: 10,
        borderRadius: 12,
        overflow: "hidden",
      },
      historyItemContent: {
        padding: 15,
      },
      historyItemHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 8,
      },
      historyItemDate: {
        fontSize: 14,
        fontWeight: "500",
        color: "white",
      },
      historyCompletedBadge: {
        backgroundColor: "#28a745",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 8,
      },
      historyCompletedText: {
        color: "white",
        fontSize: 12,
        fontWeight: "bold",
      },
      historyMissedBadge: {
        backgroundColor: "#dc3545",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 8,
      },
      historyMissedText: {
        color: "white",
        fontSize: 12,
        fontWeight: "bold",
      },
      historyItemDesc: {
        fontSize: 16,
        color: "white",
        marginBottom: 8,
      },
      historyItemDetails: {
        flexDirection: "row",
        justifyContent: "space-between",
      },
      historyItemClass: {
        fontSize: 14,
        color: "white",
      },
      historyItemScore: {
        fontSize: 14,
        color: "#28a745",
        fontWeight: "500",
      },
      emptyContainer: {
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 50,
        paddingHorizontal: 20,
      },
      emptyText: {
        fontSize: 18,
        fontWeight: "bold",
        color: "white",
        marginTop: 16,
      },
      emptySubtext: {
        fontSize: 14,
        color: "white",
        textAlign: "center",
        marginTop: 8,
      },
      fireAnimation: {
        aspectRatio: 1,
        height: 80,
      },
      achievementsContainer: {
        borderRadius: 30,
        padding: 15,
        marginHorizontal: 10,
        marginVertical: 10,
        marginBottom: 15,
        height: 170,
      },
      achievementHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 10,
      },
      achievementsTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "white",
      },
      achievementsSubtitle: {
        fontSize: 16,
        color: "#aaa",
        textAlign: "center",
        marginBottom: 20,
      },
      badgeScrollContainer: {
        paddingVertical: 5,
        height: 110,
        width: "100%",
      },
      badgeContainer: {
        width: 80,
        alignItems: "center",
        marginRight: 15,
      },
      badge: {
        width: 60,
        height: 70,
        backgroundColor: "#202020",
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 8,
        borderWidth: 2,
        borderColor: "#28a745",
        // Shield shape with custom styling
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        position: "relative",
        overflow: "hidden",
      },
      badgeContent: {
        width: "100%",
        height: "100%",
        alignItems: "center",
        justifyContent: "center",
      },
      badgeNumber: {
        fontSize: 22,
        fontWeight: "bold",
        color: "white",
        zIndex: 10,
      },
      badgeIconBox: {
        position: "absolute",
        top: 5,
        right: 5,
        width: 18,
        height: 18,
        backgroundColor: "#28a745",
        borderRadius: 9,
        alignItems: "center",
        justifyContent: "center",
      },
      badgeTitle: {
        fontSize: 11,
        color: "white",
        fontWeight: "bold",
        textAlign: "center",
      },
      badgeDate: {
        fontSize: 10,
        color: "#666",
        textAlign: "center",
      },
      lockedBadge: {
        borderColor: "#999",
        backgroundColor: "#3a3a3a",
        shadowColor: "#999",
        shadowOpacity: 0.2,
        opacity: 0.7,
      },
      streakBadge: {
        borderColor: "#E94976",
        shadowColor: "#E94976",
      },
      firstBadgeAnimation: {
        height: 65,
        width: 65,
        alignSelf: "center",
        position: "absolute", 
        top: 3,
        opacity: 1, // Always visible
      },
      firstBadge: {
        borderColor: "#FFB800",
        backgroundColor: "#202020",
        justifyContent: "center",
        alignItems: "center",
      },
      streakBadgeAnimation: {
        height: 60,
        width: 60,
        alignSelf: "center",
        position: "absolute",
        opacity: 0.5,
        top: 5,
      },
});
