import { Dimensions, StyleSheet } from "react-native";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");
export const homeStyles = StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: "#000",
      },
      cameraContainer: {
        width: Dimensions.get("window").width * 0.975,
        aspectRatio: 1,
        overflow: "hidden",
        borderRadius: 50,
        marginBottom: 100,
      },
      feedCameraContainer: {
        width: Dimensions.get("window").width * 0.975,
        aspectRatio: 1,
        overflow: "hidden",
        borderRadius: 50,
      },
      camera: {
        flex: 1,
        width: "100%",
        height: "100%",
      },
      captureButton: {
        width: 75,
        height: 75,
        borderRadius: 50,
        borderWidth: 5,
        borderColor: "#FFB800",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "transparent",
      },
      sendButton: {
        width: 95,
        height: 95,
        borderRadius: 50,
        borderWidth: 5,
        borderColor: "#FFB800",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "gray",
      },
      captureButtonInner: {
        width: 55,
        height: 55,
        borderRadius: 50,
        backgroundColor: "white",
      },
      // Feed specific styles
      feedItem: {
        width: SCREEN_WIDTH,
        height: SCREEN_HEIGHT,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#000",
      },
      feedImage: {
        width: "100%",
        height: "100%",
      },
      feedInfo: {
        position: "absolute",
        bottom: 100,
        left: 20,
        backgroundColor: "rgba(0,0,0,0.5)",
        padding: 12,
        borderRadius: 12,
        maxWidth: "70%",
      },
      feedUsername: {
        color: "white",
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 4,
      },
      feedTimestamp: {
        color: "#ccc",
        fontSize: 14,
      },
      feedIpfsBadge: {
        position: "absolute",
        right: 15,
        top: 60,
        backgroundColor: "rgba(0, 102, 204, 0.8)",
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 8,
      },
      feedLoadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#000",
      },
      feedLoadingText: {
        color: "white",
        marginTop: 10,
        fontSize: 16,
      },
      feedEmptyContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#000",
      },
      feedEmptyText: {
        color: "white",
        fontSize: 20,
        fontWeight: "bold",
        marginTop: 20,
      },
      feedEmptySubtext: {
        color: "#ccc",
        fontSize: 16,
        marginTop: 8,
        textAlign: "center",
        paddingHorizontal: 40,
      },
      feedBackButton: {
        position: "absolute",
        top: 60,
        left: 15,
        backgroundColor: "rgba(0,0,0,0.5)",
        flexDirection: "row",
        alignItems: "center",
        padding: 10,
        borderRadius: 20,
      },
      feedBackText: {
        color: "white",
        marginLeft: 8,
        fontWeight: "600",
      },
      messageBoxContainer: {
        position: "absolute",
        bottom: 150,
        left: 20,
        right: 20,
        alignItems: "center",
        transitionProperty: "all",
      },
      messageButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(0, 0, 0, 0.7)",
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 20,
      },
      messageButtonText: {
        color: "white",
        marginLeft: 8,
        fontWeight: "600",
      },
      messageInput: {
        flex: 1,
        color: "white",
        paddingVertical: 10,
        maxHeight: 80,
      },
      messageSendButton: {
        backgroundColor: "#FFB800",
        borderRadius: 20,
        width: 36,
        height: 36,
        justifyContent: "center",
        alignItems: "center",
      },
      cancelButton: {
        marginTop: 10,
        paddingVertical: 6,
        paddingHorizontal: 12,
      },
      cancelButtonText: {
        color: "#FFB800",
        fontWeight: "600",
      },
      challengeCameraContainer: {
        width: Dimensions.get("window").width * 0.975,
        aspectRatio: 1,
        overflow: "hidden",
        borderRadius: 50,
        marginBottom: 50,
      },
})