import { StyleSheet, Dimensions } from "react-native";
export const challengeCardStyles = StyleSheet.create({
  container: {
    width: Dimensions.get("window").width * 0.975,
  },
  challengeCard: {
    backgroundColor: "#23232A",
    borderRadius: 30,
    padding: 20,
  },
  challengeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  challengeTitle: { color: "#fff", fontWeight: "bold", fontSize: 18 },
  streakRow: { flexDirection: "row", alignItems: "center" },
  streakText: { color: "#FFB800", fontWeight: "bold", marginLeft: 4 },
  challengeDesc: { color: "#fff", marginTop: 8, marginBottom: 12 },
  finishBtn: {
    backgroundColor: "#FFD600",
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
  },
  finishBtnText: { color: "#18181B", fontWeight: "bold", fontSize: 16 },
  feedContainer: { flex: 1, marginTop: 8 },
  feedImageCard: {
    borderRadius: 20,
    overflow: "hidden",
    marginBottom: 16,
    width: "90%",
    backgroundColor: "#23232A",
  },
  feedImage: { width: "100%", height: 220, resizeMode: "cover" },
  locationBadge: {
    position: "absolute",
    bottom: 12,
    left: 12,
    backgroundColor: "#23232Aaa",
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  locationText: { color: "#fff", marginLeft: 4, fontWeight: "bold" },
  messageRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#23232A",
    borderRadius: 16,
    marginHorizontal: 20,
    marginBottom: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    justifyContent: "space-between",
  },
  messageInput: { color: "#fff", opacity: 0.6, fontSize: 16 },
  emojiRow: { color: "#fff", fontSize: 18 },
});
